### ISSUE TITLE
Configure repo to be a template repository

### ISSUE THREAD

**Issue by koenpunt** [apollographql/react-apollo-error-template#76]
By checking the "Template repository" checkbox in the repository settings, you allow people to use this repo as a base for their error reproduction application using only a couple of clicks.

![image](https://user-images.githubusercontent.com/351038/140580306-f28c4216-b8d6-4ea1-a15c-15cf64705c99.png)

See the [GitHub documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) for more details about template repositories.

**Comment by benjamn** [comment]
Great idea (done)—thanks @koenpunt!
